[package]
name = "myip"
version = "0.1.0"
authors = ["José Fco. Rives <jose@digio.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_if_addrs = "0.5.3"
my_internet_ip = "0.1.1"